---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  labels:
    app: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      nodeSelector:
        kubernetes.io/hostname: rayv2-cpu3
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: local-registry
spec:
  selector:
    app: local-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  clusterIP: 10.100.67.202
  type: ClusterIP

---

# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: local-registry-nodeport
spec:
  selector:
    app: local-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000  # NodePort value, optional
  type: NodePort